name: "${project.name}"
main: no.atc.floyd.bukkit.slow.SlowEdit
version: "${project.version}"
website: "${project.url}"
author: FloydATC
description: "${project.description}"

commands:
  edit:
    description: Show command usage
    usage: /<command> help
